<?php

return [
	'version'  => '5.2',
	'title'    => __( 'Posts' ),
	'type'     => 'post',
	'id'       => '60f16a6cb1b55',
	'updated'  => 1626434557,
	'columns'  => [
		'60f16bfd35867' => [
			'type'                   => 'column-featured_image',
			'label'                  => __( 'Image' ),
			'width'                  => '80',
			'width_unit'             => 'px',
			'featured_image_display' => 'image',
			'image_size'             => 'cpac-custom',
			'image_size_w'           => '60',
			'image_size_h'           => '60',
			'sort'                   => 'on',
			'edit'                   => 'off',
			'export'                 => 'off',
			'search'                 => 'on',
			'filter'                 => 'off',
			'filter_label'           => '',
		],
		'title'         => [
			'type'       => 'title',
			'label'      => __( 'Title' ),
			'width'      => '',
			'width_unit' => '%',
			'sort'       => 'on',
			'edit'       => 'off',
			'export'     => 'on',
			'search'     => 'on',
		],
		'author'        => [
			'type'       => 'author',
			'label'      => __( 'Author' ),
			'width'      => '10',
			'width_unit' => '%',
			'sort'       => 'on',
			'edit'       => 'off',
			'export'     => 'on',
			'search'     => 'on',
		],
		'categories'    => [
			'type'       => 'categories',
			'label'      => __( 'Categories' ),
			'width'      => '15',
			'width_unit' => '%',
			'sort'       => 'on',
			'edit'       => 'off',
			'export'     => 'on',
			'search'     => 'on',
			'filter'     => 'on',
		],
		'tags'          => [
			'type'         => 'tags',
			'label'        => __( 'Tags' ),
			'width'        => '15',
			'width_unit'   => '%',
			'sort'         => 'on',
			'edit'         => 'off',
			'export'       => 'on',
			'search'       => 'on',
			'filter'       => 'on',
			'filter_label' => __( 'Any Tags', 'bm-wp-experience' ),
		],
		'date'          => [
			'type'          => 'date',
			'label'         => __( 'Date' ),
			'width'         => '',
			'width_unit'    => '%',
			'sort'          => 'on',
			'edit'          => 'off',
			'export'        => 'on',
			'search'        => 'on',
			'filter'        => 'on',
			'filter_label'  => __( 'Date' ),
			'filter_format' => 'range',
		],
		'60f16bfd35869' => [
			'type'       => 'column-word_count',
			'label'      => __( 'Words', 'bm-wp-experience' ),
			'width'      => '100',
			'width_unit' => 'px',
			'sort'       => 'on',
			'export'     => 'on',
		],
		'60f16bfd3586a' => [
			'type'       => 'wpseo-score',
			'label'      => __( 'SEO', 'bm-wp-experience' ),
			'width'      => '63',
			'width_unit' => 'px',
			'sort'       => 'on',
			'export'     => 'off',
		],
	],
	'settings' => [
		'hide_inline_edit'        => 'off',
		'hide_bulk_edit'          => 'off',
		'hide_filters'            => 'off',
		'hide_filter_post_date'   => 'on',
		'hide_filter_category'    => 'off',
		'hide_filter_post_format' => 'off',
		'hide_smart_filters'      => 'off',
		'hide_segments'           => 'off',
		'hide_export'             => 'off',
		'hide_new_inline'         => 'on',
		'hide_search'             => 'off',
		'hide_bulk_actions'       => 'off',
		'horizontal_scrolling'    => 'off',
		'sorting'                 => '0',
		'sorting_order'           => 'asc',
	],
];
