<?php

return [
	'version'  => '5.2',
	'title'    => __( 'Media', 'bm-wp-experience' ),
	'type'     => 'wp-media',
	'id'       => '60f16ee483c17',
	'updated'  => 1626435537,
	'columns'  => [
		'title'         => [
			'type'       => 'title',
			'label'      => __( 'Media File', 'bm-wp-experience' ),
			'width'      => '',
			'width_unit' => '%',
			'sort'       => 'on',
			'edit'       => 'off',
			'export'     => 'on',
			'search'     => 'on',
		],
		'60f16fd1f044e' => [
			'type'         => 'column-mime_type',
			'label'        => __( 'Format', 'bm-wp-experience' ),
			'width'        => '10',
			'width_unit'   => '%',
			'sort'         => 'on',
			'edit'         => 'off',
			'export'       => 'on',
			'search'       => 'on',
			'filter'       => 'on',
			'filter_label' => __( 'Any Format', 'bm-wp-experience' ),
		],
		'60f16fd1f0450' => [
			'type'       => 'column-dimensions',
			'label'      => __( 'Dimensions', 'bm-wp-experience' ),
			'width'      => '10',
			'width_unit' => '%',
			'before'     => '',
			'after'      => 'px',
			'sort'       => 'on',
			'export'     => 'on',
		],
		'60f16fd1f0451' => [
			'type'       => 'column-alternate_text',
			'label'      => __( 'Alt Text', 'bm-wp-experience' ),
			'width'      => '10',
			'width_unit' => '%',
			'sort'       => 'on',
			'edit'       => 'off',
			'export'     => 'on',
			'search'     => 'on',
		],
		'author'        => [
			'type'         => 'author',
			'label'        => __( 'Author', 'bm-wp-experience' ),
			'width'        => '10',
			'width_unit'   => '%',
			'sort'         => 'on',
			'edit'         => 'off',
			'export'       => 'on',
			'search'       => 'on',
			'filter'       => 'off',
			'filter_label' => '',
		],
		'parent'        => [
			'type'         => 'parent',
			'label'        => __( 'Uploaded To', 'bm-wp-experience' ),
			'width'        => '15',
			'width_unit'   => '%',
			'sort'         => 'on',
			'export'       => 'on',
			'search'       => 'on',
			'filter'       => 'off',
			'filter_label' => '',
		],
		'date'          => [
			'type'          => 'date',
			'label'         => __( 'Date', 'bm-wp-experience' ),
			'width'         => '10',
			'width_unit'    => '%',
			'sort'          => 'on',
			'edit'          => 'off',
			'export'        => 'on',
			'search'        => 'on',
			'filter'        => 'on',
			'filter_label'  => __( 'Date', 'bm-wp-experience' ),
			'filter_format' => 'range',
		],
		'60f16fd1f0452' => [
			'type'       => 'column-download',
			'label'      => '',
			'width'      => '20',
			'width_unit' => 'px',
			'export'     => 'off',
		],
	],
	'settings' => [
		'hide_inline_edit'       => 'off',
		'hide_bulk_edit'         => 'off',
		'hide_filters'           => 'off',
		'hide_filter_media_type' => 'off',
		'hide_filter_post_date'  => 'on',
		'hide_smart_filters'     => 'off',
		'hide_segments'          => 'off',
		'hide_export'            => 'off',
		'hide_search'            => 'off',
		'hide_bulk_actions'      => 'off',
		'horizontal_scrolling'   => 'off',
		'sorting'                => '0',
		'sorting_order'          => 'asc',
	],
];
